<?php

namespace ShoppingListBundle\Repository;

/**
 * allergensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class allergensRepository extends \Doctrine\ORM\EntityRepository
{
}
